version: "3.9"

services:
  pgadmin:
    image: dpage/pgadmin4:9.13
    container_name: pgadmin
    restart: unless-stopped

    ports:
      - "5050:80"

    environment:
      # tài khoản đăng nhập
      PGADMIN_DEFAULT_EMAIL: huycim@gmail.com
      PGADMIN_DEFAULT_PASSWORD: strongpassword

      # cấu hình server
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_CONFIG_SERVER_MODE: "True"

      # logging
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10

      # session
      PGADMIN_CONFIG_SESSION_EXPIRATION_TIME: 60

      # upload limit
      PGADMIN_CONFIG_MAX_UPLOAD_SIZE: 1024

      # master password
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"

      # timezone
      TZ: Asia/Ho_Chi_Minh

    volumes:
      - ./pgadmin/data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json

    networks:
      - pgadmin_net


networks:
  pgadmin_net:
    driver: bridge
